const products = [
  {
    id: 'prod_001',
    name: 'Amul Butter',
    slug: 'amul-butter',
    brandId: 'brand_001',
    category: 'grocery',
    subCategory: 'dairy',
    image: '/products/amul-butter.jpg',
    description: 'Creamy table butter for toast, cooking, and baking.',
    quantity: 500,
    unit: 'g',
    price: 285,
    currency: 'INR',
    availability: true,
    tags: ['butter', 'dairy', 'amul', 'breakfast'],
  },

  {
    id: 'prod_002',
    name: 'Amul Cheese Slices',
    slug: 'amul-cheese-slices',
    brandId: 'brand_001',
    category: 'grocery',
    subCategory: 'dairy',
    image: '/products/amul-cheese.webp',
    description: 'Convenient cheese slices for sandwiches and burgers.',
    quantity: 200,
    unit: 'g',
    price: 145,
    currency: 'INR',
    availability: true,
    tags: ['cheese', 'dairy', 'amul', 'sandwich'],
  },

  {
    id: 'prod_003',
    name: 'Amul Fresh Paneer',
    slug: 'amul-fresh-paneer',
    brandId: 'brand_001',
    category: 'grocery',
    subCategory: 'dairy',
    image: '/products/amul-paneer.jpg',
    description: 'Soft paneer for curries, wraps, and quick snacks.',
    quantity: 200,
    unit: 'g',
    price: 95,
    currency: 'INR',
    availability: true,
    tags: ['paneer', 'dairy', 'amul', 'protein'],
  },

  {
    id: 'prod_004',
    name: 'Amul Gold Milk',
    slug: 'amul-gold-milk',
    brandId: 'brand_001',
    category: 'grocery',
    subCategory: 'dairy',
    image: '/products/amul-milk.webp',
    description:
      'Full cream milk for tea, coffee, desserts, and breakfast.',
    quantity: 1,
    unit: 'L',
    price: 76,
    currency: 'INR',
    availability: true,
    tags: ['milk', 'dairy', 'amul'],
  },

  {
    id: 'prod_005',
    name: 'Tata Sampann Toor Dal',
    slug: 'tata-sampann-toor-dal',
    brandId: 'brand_002',
    category: 'grocery',
    subCategory: 'pulses',
    image: '/products/toor-dal.jpg',
    description: 'Unpolished toor dal for comforting everyday meals.',
    quantity: 1,
    unit: 'kg',
    price: 178,
    currency: 'INR',
    availability: true,
    tags: ['dal', 'pulses', 'protein', 'tata sampann'],
  },

  {
    id: 'prod_006',
    name: 'Tata Sampann Turmeric Powder',
    slug: 'tata-sampann-turmeric',
    brandId: 'brand_002',
    category: 'grocery',
    subCategory: 'spices',
    image: '/products/turmeric.jpg',
    description: 'Bright turmeric powder for everyday Indian cooking.',
    quantity: 200,
    unit: 'g',
    price: 68,
    currency: 'INR',
    availability: true,
    tags: ['turmeric', 'haldi', 'spice', 'tata sampann'],
  },

  {
    id: 'prod_007',
    name: 'Tata Sampann Chilli Powder',
    slug: 'tata-sampann-chilli-powder',
    brandId: 'brand_002',
    category: 'grocery',
    subCategory: 'spices',
    image: '/products/chilli.webp',
    description: 'Red chilli powder that adds colour and heat to dishes.',
    quantity: 200,
    unit: 'g',
    price: 82,
    currency: 'INR',
    availability: false,
    tags: ['chilli', 'mirch', 'spice', 'tata sampann'],
  },

  {
    id: 'prod_008',
    name: 'Fortune Sunlite Refined Oil',
    slug: 'fortune-sunlite-oil',
    brandId: 'brand_003',
    category: 'grocery',
    subCategory: 'oils',
    image: '/products/sunflower-oil.webp',
    description: 'Refined sunflower oil for daily frying and cooking.',
    quantity: 1,
    unit: 'L',
    price: 156,
    currency: 'INR',
    availability: true,
    tags: ['oil', 'sunflower', 'cooking', 'fortune'],
  },

  {
    id: 'prod_009',
    name: 'Fortune Basmati Rice',
    slug: 'fortune-basmati-rice',
    brandId: 'brand_003',
    category: 'grocery',
    subCategory: 'rice',
    image: '/products/basmati-rice.jpg',
    description:
      'Long-grain basmati rice for pulao, biryani, and everyday meals.',
    quantity: 1,
    unit: 'kg',
    price: 189,
    currency: 'INR',
    availability: true,
    tags: ['rice', 'basmati', 'fortune'],
  },

  {
    id: 'prod_010',
    name: 'Aashirvaad Whole Wheat Atta',
    slug: 'aashirvaad-whole-wheat-atta',
    brandId: 'brand_004',
    category: 'grocery',
    subCategory: 'flour',
    image: '/products/atta.avif',
    description: 'Whole wheat flour for soft rotis and home-style breads.',
    quantity: 5,
    unit: 'kg',
    price: 315,
    currency: 'INR',
    availability: true,
    tags: ['atta', 'flour', 'wheat', 'aashirvaad'],
  },

  {
    id: 'prod_011',
    name: 'Aashirvaad Salt',
    slug: 'aashirvaad-salt',
    brandId: 'brand_004',
    category: 'grocery',
    subCategory: 'seasoning',
    image: '/products/salt.jpg',
    description: 'Iodised salt for everyday cooking and seasoning.',
    quantity: 1,
    unit: 'kg',
    price: 28,
    currency: 'INR',
    availability: true,
    tags: ['salt', 'seasoning', 'aashirvaad'],
  },

  {
    id: 'prod_012',
    name: 'Mother Dairy Curd',
    slug: 'mother-dairy-curd',
    brandId: 'brand_005',
    category: 'grocery',
    subCategory: 'dairy',
    image: '/products/curd.jpg',
    description: 'Smooth set curd for meals, raita, and snacks.',
    quantity: 400,
    unit: 'g',
    price: 52,
    currency: 'INR',
    availability: true,
    tags: ['curd', 'dahi', 'dairy', 'mother dairy'],
  },

  {
    id: 'prod_013',
    name: 'Mother Dairy Toned Milk',
    slug: 'mother-dairy-toned-milk',
    brandId: 'brand_005',
    category: 'grocery',
    subCategory: 'dairy',
    image: '/products/mother-dairy-milk.jpg',
    description: 'Toned milk for daily tea, cereals, and cooking.',
    quantity: 1,
    unit: 'L',
    price: 58,
    currency: 'INR',
    availability: true,
    tags: ['milk', 'dairy', 'mother dairy'],
  },
]

export default products